package com.ufcg.psoft.vacinaja.enums;

public enum ComorbidadesEnum{
	DOENCA_CEREBROVASCULAR,
	DOENCA_CARDIACA,
	DOENCA_RENAL_CRONICA,
	OBESIDADE,
	DIABETES,
	SINDROME_DE_DOWN,
	PNEUMOPATIA,
	IMUNOSSUPRIMIDOS,
	ANEMIA,
	CIRROSE_HEPATICA
}
