package com.ufcg.psoft.vacinaja.enums;

public enum ProfissoesEnum {
	MEDICO,
	ENFERMEIRO,
	FISIOTERAPEUTA,
	POLICIAL_FEDERAL,
	FORCAS_ARMADAS,
	AGENTE_SOCIOEDUCATIVO,
	AGENTE_PENITENCIARIO,
	TECNICO_DE_ENFEMAGEM,
	AUXILIAR_DE_ENFERMAGEM
}